### PR TITLE
Add highlight image to PopupImage

### LINKED ISSUE #173: [Feature Request] New highlight method for Popup Toolkit Controls
One of the cool feature i found with archlinux-logout (by arcolinux team) is how the icon are swapped when highlighted.
They use theme with two set of icons blurred and non blurred.
When the cursor hover on one icon.svg :
logout
It is substituted by icon_blurred.svg: 
logout_blur

The effect is quite nice.
Is it something you'll find interesting to implement as a new highlight method?

### PR DESCRIPTION
**Pull request by elParaguayo**
PopupImage can now display an alternative image as a highlight method.

Fixes #173

### CODE REVIEW

**Comment by Crystal4276** [comment]
Something wrong. Icon is not changed + other issue.
Cf video +config.

https://user-images.githubusercontent.com/27446196/201486120-31a68090-670c-4e7b-ba67-a1a2125ceede.mp4


```python
def show_power_menu(qtile):
    controls = [
        PopupImage(
            filename="~/.config/qtile/assets/lock.svg",
            pos_x=0.6,
            pos_y=0,
            width=0.4,
            height=0.2,
            highlight_method='image',
            highlight_filename="~/.config/qtile/assets/lock_blur.svg",
            #highlight=colors[6],
            mouse_callbacks={
                "Button1": lazy.spawn('betterlockscreen -l dim -- --time-str="%H:%M"')
            }
        PopupImage(
            filename="~/.config/qtile/assets/logout.svg",
            pos_x=0.6,
            pos_y=0.27,
            width=0.4,
            height=0.2,
            highlight=colors[6],
            mouse_callbacks={
                "Button1": lazy.shutdown()
            }
        ),
```

```

**Comment by Crystal4276** [comment]
qtile.log

```
2022-11-12 20:13:11,331 WARNING libqtile toolkit.py:_load_image():L1098 Image does not exist: /home/crystal/.config/qtile/assets/lock_blur.svg
2022-11-12 20:13:11,841 ERROR libqtile core.py:_xpoll():L340 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 308, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 1149, in handle_MotionNotify
    self.process_pointer_motion(e.event_x, e.event_y)
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 378, in process_pointer_motion
    control.mouse_enter(
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 806, in mouse_enter
    self.container.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 171, in draw
    c.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 735, in draw
    self.paint()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 1118, in paint
    pattern = self.img.pattern if not self._highlight else self.highlight_img.pattern
AttributeError: 'NoneType' object has no attribute 'pattern'
2022-11-12 20:13:11,973 ERROR libqtile core.py:_xpoll():L340 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 308, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 1149, in handle_MotionNotify
    self.process_pointer_motion(e.event_x, e.event_y)
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 378, in process_pointer_motion
    control.mouse_enter(
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 806, in mouse_enter
    self.container.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 171, in draw
    c.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 735, in draw
    self.paint()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 1118, in paint
    pattern = self.img.pattern if not self._highlight else self.highlight_img.pattern
AttributeError: 'NoneType' object has no attribute 'pattern'
2022-11-12 20:13:12,397 ERROR libqtile core.py:_xpoll():L340 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 308, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 1149, in handle_MotionNotify
    self.process_pointer_motion(e.event_x, e.event_y)
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 378, in process_pointer_motion
    control.mouse_enter(
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 806, in mouse_enter
    self.container.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 171, in draw
    c.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 735, in draw
    self.paint()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 1118, in paint
    pattern = self.img.pattern if not self._highlight else self.highlight_img.pattern
AttributeError: 'NoneType' object has no attribute 'pattern'
2022-11-12 20:13:12,760 ERROR libqtile core.py:_xpoll():L340 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 308, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 1149, in handle_MotionNotify
    self.process_pointer_motion(e.event_x, e.event_y)
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 378, in process_pointer_motion
    control.mouse_enter(
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 806, in mouse_enter
    self.container.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 171, in draw
    c.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 735, in draw
    self.paint()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 1118, in paint
    pattern = self.img.pattern if not self._highlight else self.highlight_img.pattern
AttributeError: 'NoneType' object has no attribute 'pattern'
```

**Comment by elParaguayo** [comment]
It says near the top that your highlight image doesn't exist

**Comment by Crystal4276** [comment]
I double checked that and indeed there was an issue.
The qtile.log above is actually updated and doesn't mention anymore that "highlight image doesn't exist"
But the same issues remains

**Comment by elParaguayo** [comment]
Well, it's definitely failing to load the image. Does that image load if you set it as the main `filename` parameter?

**Comment by Crystal4276** [comment]
Sorry actually the `highlight_method='image'` works fine.
It's just that my blurred version of the lock icon is not different enough (i should get more blur on that).
Here's the final result:

https://user-images.githubusercontent.com/27446196/201488643-498c047e-769d-4664-b25f-93028405ccac.mp4

There is still a new bug with `highlight method='block'`.
I need to check border method also in case something happened there too.

qtile.log

```python
2022-11-12 21:09:05,563 ERROR libqtile core.py:_xpoll():L340 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 308, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 1149, in handle_MotionNotify
    self.process_pointer_motion(e.event_x, e.event_y)
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 378, in process_pointer_motion
    control.mouse_enter(
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 806, in mouse_enter
    self.container.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 171, in draw
    c.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 735, in draw
    self.paint()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 1118, in paint
    pattern = self.img.pattern if not self._highlight else self.highlight_img.pattern
AttributeError: 'NoneType' object has no attribute 'pattern'
2022-11-12 21:09:08,135 ERROR libqtile core.py:_xpoll():L340 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 308, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 1149, in handle_MotionNotify
    self.process_pointer_motion(e.event_x, e.event_y)
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 378, in process_pointer_motion
    control.mouse_enter(
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 806, in mouse_enter
    self.container.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 171, in draw
    c.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 735, in draw
    self.paint()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 1118, in paint
    pattern = self.img.pattern if not self._highlight else self.highlight_img.pattern
AttributeError: 'NoneType' object has no attribute 'pattern'
```

**Comment by elParaguayo** [comment]
Ah, yes. There's a bug in the code.

**Comment by Crystal4276** [comment]
Same bug / new qtile.log 
```python
2022-11-12 21:24:36,394 ERROR libqtile core.py:_xpoll():L340 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 308, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 1149, in handle_MotionNotify
    self.process_pointer_motion(e.event_x, e.event_y)
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 378, in process_pointer_motion
    control.mouse_enter(
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 806, in mouse_enter
    self.container.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 171, in draw
    c.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 735, in draw
    self.paint()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 1118, in paint
    if self._highlight and self._highlight_method == "image":
  File "/usr/lib/python3.10/site-packages/libqtile/configurable.py", line 48, in __getattr__
    raise AttributeError("%s has no attribute: %s" % (cname, name))
AttributeError: PopupImage has no attribute: _highlight_method
2022-11-12 21:24:36,571 ERROR libqtile core.py:_xpoll():L340 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 308, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 1149, in handle_MotionNotify
    self.process_pointer_motion(e.event_x, e.event_y)
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 378, in process_pointer_motion
    control.mouse_enter(
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 806, in mouse_enter
    self.container.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 171, in draw
    c.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 735, in draw
    self.paint()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 1118, in paint
    if self._highlight and self._highlight_method == "image":
  File "/usr/lib/python3.10/site-packages/libqtile/configurable.py", line 48, in __getattr__
    raise AttributeError("%s has no attribute: %s" % (cname, name))
AttributeError: PopupImage has no attribute: _highlight_method
2022-11-12 21:24:37,011 ERROR libqtile core.py:_xpoll():L340 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 308, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 1149, in handle_MotionNotify
    self.process_pointer_motion(e.event_x, e.event_y)
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 378, in process_pointer_motion
    control.mouse_enter(
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 806, in mouse_enter
    self.container.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 171, in draw
    c.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 735, in draw
    self.paint()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 1118, in paint
    if self._highlight and self._highlight_method == "image":
  File "/usr/lib/python3.10/site-packages/libqtile/configurable.py", line 48, in __getattr__
    raise AttributeError("%s has no attribute: %s" % (cname, name))
AttributeError: PopupImage has no attribute: _highlight_method
2022-11-12 21:24:37,291 ERROR libqtile core.py:_xpoll():L340 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 308, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 1149, in handle_MotionNotify
    self.process_pointer_motion(e.event_x, e.event_y)
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 378, in process_pointer_motion
    control.mouse_enter(
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 806, in mouse_enter
    self.container.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 171, in draw
    c.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 735, in draw
    self.paint()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 1118, in paint
    if self._highlight and self._highlight_method == "image":
  File "/usr/lib/python3.10/site-packages/libqtile/configurable.py", line 48, in __getattr__
    raise AttributeError("%s has no attribute: %s" % (cname, name))
AttributeError: PopupImage has no attribute: _highlight_method
2022-11-12 21:24:37,693 ERROR libqtile core.py:_xpoll():L340 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 308, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 1149, in handle_MotionNotify
    self.process_pointer_motion(e.event_x, e.event_y)
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 378, in process_pointer_motion
    control.mouse_enter(
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 806, in mouse_enter
    self.container.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 171, in draw
    c.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 735, in draw
    self.paint()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 1118, in paint
    if self._highlight and self._highlight_method == "image":
  File "/usr/lib/python3.10/site-packages/libqtile/configurable.py", line 48, in __getattr__
    raise AttributeError("%s has no attribute: %s" % (cname, name))
AttributeError: PopupImage has no attribute: _highlight_method
2022-11-12 21:24:38,523 ERROR libqtile core.py:_xpoll():L340 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 308, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 1149, in handle_MotionNotify
    self.process_pointer_motion(e.event_x, e.event_y)
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 378, in process_pointer_motion
    control.mouse_enter(
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 806, in mouse_enter
    self.container.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 171, in draw
    c.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 735, in draw
    self.paint()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 1118, in paint
    if self._highlight and self._highlight_method == "image":
  File "/usr/lib/python3.10/site-packages/libqtile/configurable.py", line 48, in __getattr__
    raise AttributeError("%s has no attribute: %s" % (cname, name))
AttributeError: PopupImage has no attribute: _highlight_method
2022-11-12 21:24:38,797 ERROR libqtile core.py:_xpoll():L340 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 308, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 1149, in handle_MotionNotify
    self.process_pointer_motion(e.event_x, e.event_y)
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 378, in process_pointer_motion
    control.mouse_enter(
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 806, in mouse_enter
    self.container.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 171, in draw
    c.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 735, in draw
    self.paint()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 1118, in paint
    if self._highlight and self._highlight_method == "image":
  File "/usr/lib/python3.10/site-packages/libqtile/configurable.py", line 48, in __getattr__
    raise AttributeError("%s has no attribute: %s" % (cname, name))
AttributeError: PopupImage has no attribute: _highlight_method
2022-11-12 21:24:38,858 ERROR libqtile core.py:_xpoll():L340 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 308, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 1149, in handle_MotionNotify
    self.process_pointer_motion(e.event_x, e.event_y)
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 378, in process_pointer_motion
    control.mouse_enter(
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 806, in mouse_enter
    self.container.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 171, in draw
    c.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 735, in draw
    self.paint()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 1118, in paint
    if self._highlight and self._highlight_method == "image":
  File "/usr/lib/python3.10/site-packages/libqtile/configurable.py", line 48, in __getattr__
    raise AttributeError("%s has no attribute: %s" % (cname, name))
AttributeError: PopupImage has no attribute: _highlight_method
2022-11-12 21:24:44,911 ERROR libqtile core.py:_xpoll():L340 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 308, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 1149, in handle_MotionNotify
    self.process_pointer_motion(e.event_x, e.event_y)
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 378, in process_pointer_motion
    control.mouse_enter(
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 806, in mouse_enter
    self.container.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 171, in draw
    c.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 735, in draw
    self.paint()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 1118, in paint
    if self._highlight and self._highlight_method == "image":
  File "/usr/lib/python3.10/site-packages/libqtile/configurable.py", line 48, in __getattr__
    raise AttributeError("%s has no attribute: %s" % (cname, name))
AttributeError: PopupImage has no attribute: _highlight_method
2022-11-12 21:24:45,435 ERROR libqtile core.py:_xpoll():L340 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 308, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 1149, in handle_MotionNotify
    self.process_pointer_motion(e.event_x, e.event_y)
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 378, in process_pointer_motion
    control.mouse_enter(
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 806, in mouse_enter
    self.container.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 171, in draw
    c.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 735, in draw
    self.paint()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 1118, in paint
    if self._highlight and self._highlight_method == "image":
  File "/usr/lib/python3.10/site-packages/libqtile/configurable.py", line 48, in __getattr__
    raise AttributeError("%s has no attribute: %s" % (cname, name))
AttributeError: PopupImage has no attribute: _highlight_method
2022-11-12 21:24:45,572 ERROR libqtile core.py:_xpoll():L340 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 308, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 1149, in handle_MotionNotify
    self.process_pointer_motion(e.event_x, e.event_y)
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 378, in process_pointer_motion
    control.mouse_enter(
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 806, in mouse_enter
    self.container.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 171, in draw
    c.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 735, in draw
    self.paint()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 1118, in paint
    if self._highlight and self._highlight_method == "image":
  File "/usr/lib/python3.10/site-packages/libqtile/configurable.py", line 48, in __getattr__
    raise AttributeError("%s has no attribute: %s" % (cname, name))
AttributeError: PopupImage has no attribute: _highlight_method
2022-11-12 21:24:45,597 ERROR libqtile core.py:_xpoll():L340 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 308, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 1149, in handle_MotionNotify
    self.process_pointer_motion(e.event_x, e.event_y)
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 378, in process_pointer_motion
    control.mouse_enter(
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 806, in mouse_enter
    self.container.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 171, in draw
    c.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 735, in draw
    self.paint()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 1118, in paint
    if self._highlight and self._highlight_method == "image":
  File "/usr/lib/python3.10/site-packages/libqtile/configurable.py", line 48, in __getattr__
    raise AttributeError("%s has no attribute: %s" % (cname, name))
AttributeError: PopupImage has no attribute: _highlight_method
2022-11-12 21:24:45,776 ERROR libqtile core.py:_xpoll():L340 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 308, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 1149, in handle_MotionNotify
    self.process_pointer_motion(e.event_x, e.event_y)
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 378, in process_pointer_motion
    control.mouse_enter(
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 806, in mouse_enter
    self.container.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 171, in draw
    c.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 735, in draw
    self.paint()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 1118, in paint
    if self._highlight and self._highlight_method == "image":
  File "/usr/lib/python3.10/site-packages/libqtile/configurable.py", line 48, in __getattr__
    raise AttributeError("%s has no attribute: %s" % (cname, name))
AttributeError: PopupImage has no attribute: _highlight_method
2022-11-12 21:24:45,992 ERROR libqtile core.py:_xpoll():L340 Got an exception in poll loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/core.py", line 308, in _xpoll
    ret = target(event)
  File "/usr/lib/python3.10/site-packages/libqtile/backend/x11/window.py", line 1149, in handle_MotionNotify
    self.process_pointer_motion(e.event_x, e.event_y)
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 378, in process_pointer_motion
    control.mouse_enter(
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 806, in mouse_enter
    self.container.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 171, in draw
    c.draw()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 735, in draw
    self.paint()
  File "/usr/lib/python3.10/site-packages/qtile_extras/popup/toolkit.py", line 1118, in paint
    if self._highlight and self._highlight_method == "image":
  File "/usr/lib/python3.10/site-packages/libqtile/configurable.py", line 48, in __getattr__
    raise AttributeError("%s has no attribute: %s" % (cname, name))
AttributeError: PopupImage has no attribute: _highlight_method
```

**Comment by Crystal4276** [comment]
Hahaha, it's fine now. Border works too.

Great ! Thanks a lot.

**Pull request merged**
