### PR TITLE
Fix masked image bug

### LINKED ISSUE #212: [Bug] Image.widget and mask=True doesn't draw image.
Qtile.log
```2022-11-30 23:41:43,231 ERROR libqtile images.py:draw():L69 Cannot draw masked image. Did you forget to attach the drawer?```

config
```python
                widget.Image(
                       filename="~/.config/qtile/assets/bar_icons/cpu.svg",
                       background = colors[4],
                       colour= colors[3],
                       mask=True,
                       scale=True,
                       margin_y = 16, 
                       #**decor_general
                ),
```

### PR DESCRIPTION
**Pull request by elParaguayo**
Forgot to add the line to attach the widget's `drawer` object to the image...

Fixes #212

### CODE REVIEW

**Comment by Crystal4276** [comment]
Ok, working fine !

**Comment by Crystal4276** [comment]
Here's the results.
A status bar with SVG icon colors colored by mask.
image

Still have a small issue tough, it's again the vertical alignment of text versus the position of icon.
At this point, is it a bug report on qtile github for the text not being centered ?
Or a feature request on qtile-extra for offset_y with Image.widget ?

**Comment by elParaguayo** [comment]
The qtile-extras widget has a different `draw` method so it's easier just to add the offset here.

**Comment by elParaguayo** [comment]
@Crystal4276 when you get a chance, please check if the x/y adjustments work as needed for you.

**Comment by Crystal4276** [comment]
Just did. It both worked.
Adjust_y was my main use.

Regarding adjust_x, it is not useful if not coupled to padding_x. 
The image is clipped otherwise on both direction if adjust_x !=0

**Comment by elParaguayo** [comment]
I added `adjust_x` mainly for anyone who uses this in a vertical bar as it then can be used like `padding_y` in horizontal bars. Agreed that you shouldn't really need it.

**Comment by Crystal4276** [comment]
> Agreed that you shouldn't really need it.
With Rect_Decoration having padding + adjust_x enabled on the Analogclock.widget was actually very useful.
I could use those two options to position easily the clock vs the edge of Rect_decoration and the next widget.

For the Image.widget, i had to use a workaround with two additional Spacer.widget embedded in the same Rect_Decoration before and after.
I would say that padding_x is not mandatory but just "a nice to have"

**Comment by Crystal4276** [comment]
image
All aligned !
It's only a two pixels offset... :-)

**Comment by elParaguayo** [comment]
The `Image` width doesn't adjust its size for `padding`. Should I add that too?

**Comment by Crystal4276** [comment]
> The `Image` width doesn't adjust its size for `padding`. Should I add that too?

I'm not sure to understand.
I use margin to set the size of the image.
And i use padding to add space left and right.

So in my mind only one parameter should affect the size (and for horizontal bar i'm happy with margin_y)

**Comment by Crystal4276** [comment]
Oh, it does remind me your PR where we were discussing this :
https://github.com/qtile/qtile/pull/4008

**Comment by elParaguayo** [comment]
> > The `Image` width doesn't adjust its size for `padding`. Should I add that too?
> 
> I'm not sure to understand. I use margin to set the size of the image. And i use padding to add space left and right.
> 
> So in my mind only one parameter should affect the size (and for horizontal bar i'm happy with margin_y)

How are you using `padding` with this widget? From what I can tell setting that should (currently) have no impact at all.

**Comment by Crystal4276** [comment]
I use padding and margin with analogclock. I'm just saying that a user would expect "standard" for manipulating size and position across different widgets. The way analogclock works, seems a good "standard"

**Comment by elParaguayo** [comment]
I suspect these may be used the wrong way round... On the web, `margin` is the spacing outside an object's border and `padding` is the spacing between the border and the contents.

Here, `margin` is the space around the contents and, if we added it, `padding` would be additional space outside.

**Comment by Crystal4276** [comment]
> Here, `margin` is the space around the contents and, if we added it, `padding` would be additional space outside.

I might be wrong but that is how all qtile widget are configured so far.

>I suspect these may be used the wrong way round... On the web, margin is the spacing outside an object's border and padding is the spacing between the border and the contents.

Because of this, i was surprised initially how Qtile was behaving when i started configuring the bar.
After a while, you get used to it.

**Comment by Crystal4276** [comment]
Nice !
5 spacer.widgets removed thanks to padding option and for the same bar:
image

**Comment by elParaguayo** [comment]
Great. Let me squash this and get it merged.

**Pull request merged**
