### PR TITLE
Improvements for StatusNotifier menus

### LINKED ISSUE #154: [Feature request] Cosmetic improvements for menu generated by status.notifier widget
Some cosmetic suggestions based on the rofi launcher i'm using (cf picture)

Screenshot from 2022-11-03 19-39-38

To achieve a similar result, i'd like to use three additional options:
**- rounded corner for highlight**  (pink rounded highlight in rofi screen shot)
Using picom with rounded corner is problematic if the first highlight on the menu is rectangular.
And it's still a nice feature to have anyway.

**- font_color_highlight.** 
We have a highlight_colour option. The problem is that the color we can effectively chose for highlight is rather limited. This is because the font color of the highlighted text  cannot be changed.
As an illustration, the rofi screenshot show that with the pink highlight the text color is changed to almost black to allow its visibility.

**- font_color_disabled.** 
An option to chose the font color of items that cannot be selected/highlighted.

### PR DESCRIPTION
**Pull request by elParaguayo**
Add:
- Ability to round menu highlighting
- Different font colour for highlighted items
- Ability to set menu icon size

Closes #154

### CODE REVIEW

**Comment by Crystal4276** [comment]
Hi !
I can't open any menu.
And i get this error trying :
```2022-11-05 15:24:16,889 ERROR libqtile loop.py:_handle_exception():L63 RGB specifier must be 3, 6 or 8 characters long.```

**Comment by elParaguayo** [comment]
Really? What the hell have I done?!

Can you show your config for the widget?

**Comment by Crystal4276** [comment]
I haven't tried yet to modify my config.
It's the one i was using before modifying the three  .py files.

```python
                widget.StatusNotifier(
                       icon_size=32,
                       icon_theme="/usr/share/icons/Papirus-Dark",
                       padding = 8,
                       hide_after=0.1,
                       menu_width=385,
                       show_menu_icons=True, 
                       background=colors[1],
                       highlight_colour=colors[6],
                       menu_background=colors[1],
                       menu_foreground=colors[0],
                       separator_colour=colors[15],
                       menu_fontsize = 16,
                       **decor_exit,
				),
```python
# Decoration setting for no grouping Rect.Decoraction
decor_exit = {
    "decorations": [
        RectDecoration(
            #colour="#45475a",
            use_widget_background=True,
            line_width= 0,
            radius=[15, 15, 15, 15],
            filled=True,
            padding_y=10,
            padding_x=0,
            group=True,
            clip=True,
            #extrawidth=-10,
        )
    ],
}
```

**Comment by elParaguayo** [comment]
Should work now.

**Comment by Crystal4276** [comment]
for `highlight_radius` i think there is an error somewhere regard radius value (a factor 2).
It's seems the effective radius applied is double of the value defined for `highlight_radius`

**Comment by Crystal4276** [comment]
I think there is an issue with `highlight_radius`.
The effective radius applied is double of the chosen value.
For instance: 30 instead of 15.

I can see that by comparing rounded corners those of RectDecoration.

**Comment by Crystal4276** [comment]
Very nice progresses !

Some additional minor tweaks i could pick up while testing.
I think the menu icon should also receive the color of : menu_foreground_highlighted.
Also the rounded corners comes too close to the icon. Some extrawidth applied on the left of highlight should help.
Illustration:
Screenshot from 2022-11-06 11-03-40
The arrow looks a bit disproportionate. 
Can those by impacted either by menu_icon_size /menu_fontsize  or have their own size setting ?

Something that i don't understand playing with menu_icon_size. 
It's perfectly working with nm-applet/blueman. 
But for the discord tray, the icon in its menu is not affected:
Screenshot from 2022-11-06 11-15-02

I'm wondering also if more space is needed on the left of the icons in general, and if icons are too close to the menu entry.

**Comment by Crystal4276** [comment]
> Sorry i'm probably not clear in my explanations. I'm just saying that `menu_foreground` is able to change color of text + icon (irrespective of any highlight) (cf above screenshot where i could turn all icon colors into pink) If `menu_foreground` can change icon color, i'm assuming that there is probably a way to do it differently when highlighted ?

Oh, it seems like the icons on the left of nm-applet menu are not icons ? Just some kind of symbol from a font ?

**Comment by elParaguayo** [comment]
> Some additional minor tweaks i could pick up while testing. I think the highlighted menu icon should also receive the color of : menu_foreground_highlighted.

How? The icon's colour is defined by the app so I don't have different image data to use. I *could* use the image as a mask and then provide a solid version of the icon when highlighted but that's making much more work.

> Also the rounded corners comes too close to the icon. Some extrawidth applied on the left of highlight should help. 

That's fair.

> The arrows looks a bit disproportionate. Can those be impacted either by menu_icon_size /menu_fontsize or have their own size setting ?

Agreed. Good ideas.


> Something that i don't understand playing with menu_icon_size. It's perfectly working with nm-applet/blueman. But for the discord tray, the icon in its menu is not affected:

Can you try making it much smaller/bigger and see if it changes?

> I'm wondering also if more space is needed on the left of the icons in general, and if icons are too close to the menu entry.

Isn't that the same point as the rounded corners coming too close to the icons? I don't disagree though.

**Comment by Crystal4276** [comment]
>How? The icon's colour is defined by the app so I don't have different image data to use.

Hum i don't think so. The icon color is at the moment affected by menu_foreground.
Screenshot from 2022-11-06 11-31-23

>Can you try making it much smaller/bigger and see if it changes?
Sorry it changes actually. I didn't notice because the icons from nm-applet were much more affected than the one from discord. The latter looks always much smaller in comparaison.

> Isn't that the same point as the rounded corners coming too close to the icons? I don't disagree though.

Let's see how it looks with some highlight extrawidth ?

**Comment by elParaguayo** [comment]
Ahhh. I think we're confusing icons (which are defined by the app) and the check boxes which the widget draws. I can certainly change the check box colour on the highlight.

**Comment by elParaguayo** [comment]
Weird, my reply got posted higher up. Here it is again:

Ahhh. I think we're confusing icons (which are defined by the app) and the check boxes which the widget draws. I can certainly change the check box colour on the highlight.

**Comment by elParaguayo** [comment]
Some clock has gone wrong - there are two replies below mine which are from the future!

**Comment by elParaguayo** [comment]
Is the highlight just drawing over the icon? It's certainly not doing anything to the colour of the icon itself.

**Comment by Crystal4276** [comment]
Yes i have the same issue.

I tried to post something about highlight radius in case you missed it

**Comment by Crystal4276** [comment]
"Is the highlight just drawing over the icon? It's certainly not doing anything to the colour of the icon itself."
Yes i agree.

Sorry i'm probably not clear in my explanations. I'm just saying that `menu_foreground` is able to change color of text + icon (irrespective of any highlight) (cf above screenshot where i could turn all icon colors into pink)
If `menu_foreground` can change icon color, i'm assuming that there is probably a way to do it when highlighted ?

**Comment by elParaguayo** [comment]
Have pushed some changes which give more space to the left of the icon, resize the submenu icon size and fix the highlighting on the check box.

**Comment by elParaguayo** [comment]
Hopefully fixed the overlapping menu issue too.

**Comment by Crystal4276** [comment]
> Have pushed some changes which give more space to the left of the icon, resize the submenu icon size and fix the highlighting on the check box.

Tested everything all of that look right !

We miss one last thing it's the arrow not taking color corresponding to menu_foreground_highlighted :
Screenshot from 2022-11-06 14-35-05

And one minor detail. It looks like that `highlight_radius` take the double of the defined value.
For instance if i want 15, i get 30.

**Comment by elParaguayo** [comment]
> Tested everything, all of that look right !

Nice.

> We miss one last thing it's the arrow not taking color corresponding to menu_foreground_highlighted

OK. Easy fix.

> And one minor detail. It looks like that `highlight_radius` take the double of the defined value. For instance if i want 15, i get 30.

Are you sure? How do you know it's 30? There's no doubling in the code.

**Comment by Crystal4276** [comment]
> Are you sure? How do you know it's 30? There's no doubling in the code.

I'm guessing there is a doubling factor by comparing rounded corners from RectDecoration from qtile bar and picom.
On the screenshot, Rectdecoration and picom are both set with a radius of 15.
For the highlight corner i also set 15. 
You can see the difference.
Screenshot from 2022-11-07 07-41-11

If i want to get the same radius i need to setup the radius of highlight corners to 7.5 
Screenshot from 2022-11-07 07-47-11

**Comment by Crystal4276** [comment]
Otherwise borders are working nicely.

If we could add two parameters to allow user shifting the menu position on x and y axis ?

**Comment by elParaguayo** [comment]
Is the picom radius in pixels? I can see the difference but I'm pretty sure there's no doubling in my code (it's the same code as the RectDecoration rounding).

**Comment by Crystal4276** [comment]
> Is the picom radius in pixels? I can see the difference but I'm pretty sure there's no doubling in my code (it's the same code as the RectDecoration rounding).

Yes the picom radius is in pixel.
I tried to compare with RectDecoration in more details.
Well you are right, it's not factor 2. But still it does appears a bit different.

But to be honest i don't think it's a big deal. 
The radius can be adjusted until one is happy about it.

**Comment by elParaguayo** [comment]
I've added a commit which should allow you to adjust the menu position.

**Comment by Crystal4276** [comment]
Tested and perfectly adjusted !
Thanks you 
Screenshot from 2022-11-08 09-33-27

**Pull request merged**
