### PR TITLE
Improve popup positioning

### LINKED ISSUE #176: [Feature request] Relative positioning of popup
As far as i understand the show function can only center the popup in the middle of the screen or locate it with absolute coordinates. 
It could be useful to provide also relative positioning, especially when the qtile configuration is moved to different monitor configuration/resolution.

For instance, we would have those four reference points which are the screen edges: 
```top_left, top_right, bottom_left, bottom_right.```
And those two options below would shift the popup vs. those reference points:
```offset_x, offset_y```

### PR DESCRIPTION
**Pull request by elParaguayo**
Adds ability to position popups relative to:
- any corner of the screen
- any midpoint of the screen edges
- centre of the screen

Fixes #176

### CODE REVIEW

**Comment by Crystal4276** [comment]
That was fast !!!
So I tested the 9 positions: It works fine.

One small detail i'm wondering. 
I don't have the answer.
Will it make more sense to always use positive values for x and y?
For this position:
image
I used:
```layout.show(x=-4, y=66, warp_pointer=False,relative_to=3)```
So x is negative. Not a big deal.
But maybe for in terms of user "friendliness", keeping positive values to describe the x,y offset would alleviate some confusion.

**Comment by Crystal4276** [comment]
I will test the others monitors tomorrow.

**Comment by elParaguayo** [comment]
I wondered about that positive/negative point too. I think it would be confusing to mix them so I think it may be better just to clarify in the docs that a positive X value moves the popup right etc.

**Comment by Crystal4276** [comment]
> I wondered about that positive/negative point too. I think it would be confusing to mix them so I think it may be better just to clarify in the docs that a positive X value moves the popup right etc.

Agreed

**Comment by Crystal4276** [comment]
About multi-monitors with:
`layout.show(x=-4, y=66, warp_pointer=False,relative_to=3)`
With this PR, it solves the issue regarding the popup going to neverland.

But i feel something could be improved for the "fine tuning" part.

Screen 1: 1920x1080
Screenshot from 2022-11-12 08-57-52
Screen 0: 3440x1440
Screenshot from 2022-11-12 08-58-33

The gap between the qtile bar and popup looks wider on screen 1.
It's probably because an offset of y=66 on screen 1 is 6.1% of the screen height, while on screen 0 it's only 4.6%.
So i'm wondering if an additional offset option using of % of screen width (x) and height (y) would work better ?

Also i think that one of the common use case of popup is to generate some dropdown menu initiated from qtile bar. I'm wondering if an option such as `relative_to=top.qtilebar` would also help.
This is because the qtile bars i'm using have different height on the 3440x1440 and 1920x1080 monitors.

**Comment by elParaguayo** [comment]
That's funny. I was thinking about adding a "relative to the bar" option just now so that it would automatically offset by the width of the bar. I think it would be a separate option so it could add the extra offset to each of the existing options (excluding the one in the middle of the screen).

Why is the positioning different on your different screens? Is that just a function of pixel density? It would be easy enough to add a percentage option but I'm not certain it will fix your issue.

**Comment by elParaguayo** [comment]
I'm working out the best way to include this in my tests but I've pushed the update for you anyway.

**Comment by Crystal4276** [comment]
Using this setting below, i can get a consistent positioning of the popup across the three different screens.
`layout.show(x=-6, y=0.003, warp_pointer=False,relative_to=3,relative_to_bar=True)`

So, i'm happy with this new option.

**Comment by elParaguayo** [comment]
Great. I think we can get this one merged then.

**Pull request merged**
