### PR TITLE
Fix and improve `AnalogueClock`

### LINKED ISSUE #206: [Feature request] Some options for analog.clock
The final goal would be to get rid of the clock icon displayed inside widget.Clock and replace it by analog.clock.

I would need a few additional options to achieve this goal.
This is what i could get so far :
image

Additional options:
- minute_colour
- hour_colour
- margin parameter splitted in margin_x and margin_y (i'm using margin to tune the widget size. But this introduce extra space on x-axis) 
- offset_y (tune the position of the clock on y-axis to match text position)

```python
                widget.AnalogueClock(
                    face_shape='circle',
                    face_border_width=3,
                    margin=20,
                    # ~ padding=20,
                    hour_length=0.45,
                    minute_length=0.7,
                    background=colors[7], 
                    minute_colour=colors[10],
                    face_border_colour=colors[10],
                    **decor_general, 
                ),
                widget.Clock( 
                       font="Symbols Nerd Font Mono",
                       padding = 0,
                       foreground = colors[10],
                       background=colors[7],
                       fontsize = 26,
                       format="  %H:%M",
                       **decor_general, 
                ),
```

### PR DESCRIPTION
**Pull request by elParaguayo**
`AnalogueClock` had a little bug in it which should now be fixed (failed to initialise a variable correctly).

Added ability to fine tune position of clock via new `adjust_x/y` parameters.

Fixes #206

### CODE REVIEW

**Comment by Crystal4276** [comment]
I just learned what a Class is and so I got a bit less afraid of touching stuffs.

I got it to work as i wanted.
Now i have cute "dynamic" icon !
image

I have modified L80:
`self.length = self.bar.size + 2 * (self.padding - self.margin)`
and L125
`                self.bar.size // 2 - self.margin + self.padding + self.adjust_x,`

**Comment by elParaguayo** [comment]
Did you not adjust 105 as well?

L125 adjusts the centre for drawing the circle but L105 is the centre for the hands.

**Comment by elParaguayo** [comment]
That dynamic icon looks really nice!

**Comment by Crystal4276** [comment]
Yes sorry i forgot  this block (**L103-106**)
``` python
self.drawer.ctx.translate(
            self.bar.size // 2 + self.padding + self.adjust_x - self.margin,
            self.bar.size // 2 + thickness // 2 + self.adjust_y,
        )
```
Hum, is it possible to propose suggestions in github on opened PR ? 
I mean not like i'm doing at the moment.
If i could send the file with modifications and you could see directly what's different ?

**Comment by elParaguayo** [comment]
Yes. I'll update the PR for this.

**Comment by Crystal4276** [comment]
All good !

**Pull request merged**
