### PR TITLE
Add PowerLineDecoration

### LINKED ISSUE #90: [ToDo] Add powerline window decoration
Must be possible to make a decoration that replicates the powerline effect but without the need to use text widgets in between every widget...

### PR DESCRIPTION
**Pull request by elParaguayo**
Adds ability to draw arrows, slants, curves as used for the powerline effect. Ricers will hopefully enjoy this one!

Closes #90

### CODE REVIEW

**Comment by jx11r** [comment]
I tried to test it, but got this error: https://dpaste.org/tzkSy
Hmm... this doesn't happen on 159eb19b9e796b7b685c8806c40cca709ed25f59
- qtile: 0.21.1.dev89+gc8d3aad1
- qtile-extras: 0.1.dev141+g6b4510c

**Comment by elParaguayo** [comment]
Hmm, can you share your config? I'm not sure that's an issue with this code (at least, I can't recreate on my system).

**Comment by jx11r** [comment]
I also think it's my config: [jx11r/qtile](https://github.com/jx11r/qtile)
But I'm not sure why, maybe the problem is `extras/textbox.py`

**Comment by jx11r** [comment]
@elParaguayo I can't use the TextBox widget, I've tried this minimal config:
```py
from libqtile import bar, layout
from libqtile.config import Click, Drag, Group, Key, Match, Screen
from libqtile.lazy import lazy
from libqtile.utils import guess_terminal

from qtile_extras import widget

mod = "mod4"
terminal = guess_terminal()

keys = [
  Key([mod], "space", lazy.layout.next(), desc="Move window focus to other window"),
  Key([mod], "Return", lazy.spawn(terminal), desc="Launch terminal"),
  Key([mod], "Tab", lazy.next_layout(), desc="Toggle between layouts"),
  Key([mod], "w", lazy.window.kill(), desc="Kill focused window"),
  Key([mod, "control"], "r", lazy.reload_config(), desc="Reload the config"),
  Key([mod, "control"], "q", lazy.shutdown(), desc="Shutdown Qtile"),
  Key([mod], "r", lazy.spawncmd(), desc="Spawn a command using a prompt widget"),
]

groups = [Group(i) for i in "12345"]

for i in groups:
  keys.extend([
    Key([mod], i.name, lazy.group[i.name].toscreen(toggle=True)),
    Key([mod, "shift"], i.name, lazy.window.togroup(i.name, switch_group=True)),
  ])

layouts = [
  layout.Max(),
  layout.MonadTall(
    single_border_width = 0,
    border_width = 0,
    single_margin = 15,
    margin = 15,
  ),
]

widget_defaults = dict(
  font = "sans",
  fontsize = 12,
  padding = 3,
)

screens = [
  Screen(
    bottom = bar.Bar(
      [
        widget.TextBox(text = 'test'),
      ],
      24,
    )
  ),
]

mouse = [
  Drag([mod], "Button1", lazy.window.set_position_floating(), start=lazy.window.get_position()),
  Drag([mod], "Button3", lazy.window.set_size_floating(), start=lazy.window.get_size()),
  Click([mod], "Button2", lazy.window.bring_to_front()),
]

dgroups_key_binder = None
dgroups_app_rules = [] # type: list
follow_mouse_focus = True
bring_front_click = False
cursor_warp = False
floating_layout = layout.Floating(
  float_rules = [
    *layout.Floating.default_float_rules,
    Match(wm_class="confirmreset"),
    Match(wm_class="makebranch"),
    Match(wm_class="maketag"),
    Match(wm_class="ssh-askpass"),
    Match(title="branchdialog"),
    Match(title="pinentry"),
  ]
)
auto_fullscreen = True
focus_on_window_activation = "smart"
reconfigure_screens = True
auto_minimize = True
wl_input_rules = None
wmname = "LG3D"
```

But the problem persists:
```py
Exception in callback Qtile.call_soon.<locals>.f() at /usr/lib/python3.10/site-packages/libqtile/core/manager.py:850
handle: <Handle Qtile.call_soon.<locals>.f() at /usr/lib/python3.10/site-packages/libqtile/core/manager.py:850>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.10/site-packages/libqtile/core/manager.py", line 851, in f
    func(*args)
  File "/usr/lib/python3.10/site-packages/libqtile/bar.py", line 559, in _actual_draw
    self._resize(self.length, self.widgets)
  File "/usr/lib/python3.10/site-packages/libqtile/bar.py", line 450, in _resize
    offset += i.length
  File "/usr/lib/python3.10/site-packages/qtile_extras-0.1.dev141+g6b4510c-py3.10.egg/qtile_extras/widget/decorations.py", line 508, in length_get
    length = int(self.calculate_length())
  File "/usr/lib/python3.10/site-packages/libqtile/widget/base.py", line 527, in calculate_length
    return min(self.layout.width, self.bar.width) + self.actual_padding * 2
  File "/usr/lib/python3.10/site-packages/libqtile/drawer.py", line 81, in width
    return self.layout.get_pixel_size()[0]
  File "/usr/lib/python3.10/site-packages/libqtile/pangocffi.py", line 138, in get_pixel_size
    pango.pango_layout_get_pixel_size(self._pointer, width, height)
TypeError: initializer for ctype 'PangoLayout *' must be a cdata pointer, not NoneType
```

**Comment by elParaguayo** [comment]
Interesting. I don't get the same error but I also can't create a textbox _without_ a decoration (it works with the decoration).

**Comment by elParaguayo** [comment]
Found the bug!

Have been making other changes to the code too (which you may have seen on Discord). Will push changes later but may not be until tomorrow.

**Comment by elParaguayo** [comment]
Should be working now - NB customisation is different in the latest commit.

**Comment by jx11r** [comment]
Well, it's working now, you've done an amazing job!
- With nerd fonts:
image
- With qtile-extras:
image

**Comment by elParaguayo** [comment]
Is that last screenshot really with qtile-extras? I haven't done the padding yet on the powerline decoration to it should be drawing to the edges of the bar.

**Comment by jx11r** [comment]
I'm not using the padding, it's a simple border with the same background color.
```py
bar = {
  'background': color['bg'],
  'border_color': color['bg'],
  'border_width': 4,
  'margin': [10, 10, 0, 10],
  'opacity': 1,
  'size': 18,
}
```
bar

**Comment by elParaguayo** [comment]
Ah. Cool.

**Pull request merged**
