### PR TITLE
transfer ownership

### PR DESCRIPTION
**Pull request by m-col**
this just felt right, y'know?

### CODE REVIEW

**Comment by elParaguayo** [comment]
Ha. Nice.

This may not work as it's outside the qtile_extras root but let's see what happens once the tests complete.

**Comment by elParaguayo** [comment]
Ooh. Cool. It does work.

**Comment by m-col** [comment]
Nice

**Comment by elParaguayo** [comment]
Can you add a new file in `qtile_extras` and push that.

CI should fail as the default is to fail where you reduce the overall coverage or the coverage for the new code is not equal to the current coverage level.

**Comment by elParaguayo** [comment]
Failed the PEP8 test
```
qtile_extras/foo.py:43:27: F821 undefined name 'Bar'
```

**Comment by elParaguayo** [comment]
Nice! It worked.

**Comment by m-col** [comment]
Pretty cool - how come the results are posted here and not just printed in the github action output?

**Comment by elParaguayo** [comment]
I guess because they are separate checks. My CI just uploads the pytest coverage report. It's much more visible this way.

Is that a problem?

**Pull request closed without merging**
