### PR TITLE
Add font_colour to the network widget

### PR DESCRIPTION
**Pull request by igorepst**
Adds the font color to the network widget to be able to change the color of the details text. As far as I understand the docs are generated automatically

### CODE REVIEW

**Comment by elParaguayo** [comment]
Looks good. Thanks.

**Comment by elParaguayo** [comment]
Actually... Can you change the parameter name to `foreground` to be consistent with other qtile widgets?

**Comment by igorepst** [comment]
Yes, I will tomorrow. However, I copied the name from your UPowerWidget ;)

**Comment by igorepst** [comment]
@elParaguayo Done. Thanks!

**Comment by elParaguayo** [comment]
> Yes, I will tomorrow. However, I copied the name from your UPowerWidget ;)

Ha. I'll fix that separately as I'll need to add a deprecation warning about the change in parameter name too.

**Comment by igorepst** [comment]
Same holds for the brightness widget and, possibly, other ones

**Comment by elParaguayo** [comment]
Make sense. I wrote most of those when I first started using qtile (and before I joined the team).

Will review them all later.

**Pull request merged**
