### PR TITLE
Global menu

### PR DESCRIPTION
**Pull request by elParaguayo**
First go at adding a widget implementing the `com.canonical.AppMenu.Registrar` specification.

There will undoubtedly be bugs with this!

globalmenu

To Do:
- [x] Add test
- [ ] Get working on Wayland (EDIT: Nope. Not going to work for now as the Wayland backend doesn't track the same window IDs that are sent to the registrar. May be something we can fix in the future)

### CODE REVIEW

**Comment by skela** [comment]
To Do:

Restarting qtile causes the Global Menu to die - Forcing you to log out and log in again to get the menus back.

**Comment by elParaguayo** [comment]
Thanks for that. I'm not sure how easy that will be to fix but will take a look!

**Comment by elParaguayo** [comment]
> To Do:
> 
> * [ ]  Restarting qtile causes the Global Menu to die - Forcing you to log out and log in again to get the menus back.

This is actually proving hard to fix. What's happening is that, when `restart` is called, the registrar is stopped and a new one is started with the new qtile process. However, open windows are not re-registering with the registrar so the widget doesn't know anything about them.

I'm not sure there's much I can do about this as there's no method to force active windows to re-register.

**Comment by skela** [comment]
@elParaguayo that's fine if u cant fix it 100% here, i did not even realise it was the window having to re-register.
Can confirm that if you close the window and reopen it for the window you had open, it does reload the global menu again.

So maybe a fix is just a comment in the docs or something if you think there's a place that makes sense.

This is awesome though, certainly fixed for me ;D ❤️

**Comment by elParaguayo** [comment]
Think I've got it working for you.

**Comment by elParaguayo** [comment]
@skela If you're able to check this latest commit and confirm it fixes your issue then I'll go ahead and merge this.

**Comment by skela** [comment]
@elParaguayo i gave it a go - problem remains.

Tried to change the REGISTRAR_CACHE to see if it might be a permission thing for the cache file, since the file never shows up in my tmp folder.

The way im testing this is i bring up a program that has a menu that works with the global menu, for example vs code or slack.
I then restart qtile using my keyboard short cut of mod + shift + r which fires off "lazy.restart()".

**Comment by elParaguayo** [comment]
Hmm.

Thanks for testing.

You may not actually see the file as it's created just before restart and removed as soon as the contents have been loaded after restart.

If it is a permission error, there should be a message in your logs, can you check?

I've just run `code` and the menus are still available after restart. Also tested with `vlc`.

**Comment by skela** [comment]
@elParaguayo yeah, its the only thing i could think of, but yeah, i kinda expected you to clean up after yerself, causing me not the see the file.

I'd love to check the logs, do you know the location of the log file you need me to check? (Sorry for asking, i should probably know this, but i dont)

**Comment by elParaguayo** [comment]
`~/.local/share/qtile/qtile.log`

**Comment by skela** [comment]
yeah nothing interesting in the logs regarding permissions

**Comment by elParaguayo** [comment]
Well, there are plenty of log messages that _shouldn't_ be there but that's just because I forgot to tidy them up!

If you're happy, editing the code, can you the`def load_state(self)` method state and add
``` python
logger.warning(f"LOADED: {self.windows=}")
```
before the `unlink()` call at the end of the method.

Then start up qtile, load `code`, restart and look in the logs for that line beginning `LOADED`.

**Comment by elParaguayo** [comment]
Actually, can you comment out the `unlink()` call at the end of the method so the file doesn't get deleted after restart. You can then check the file contents (NB the file will still get deleted when you shutdown qtile).

**Comment by skela** [comment]
Yeah tried with and without the unlink line. 
Didnt see the loaded call, so added a logging statement in the exception for file not found, which does fire, so the file does not seem to exist?

**Comment by elParaguayo** [comment]
Ok. Odd.

Try adding a logger statement at the start of the `dump_state` method. Let's see if the method is even being called!

**Comment by skela** [comment]
Yes yer hunch was correct, method isnt being called.

**Comment by elParaguayo** [comment]
Ok. Getting closer.

In the widget's `finalize` method (the very last method in the file), can you add a logger message just saying "Widget finalised" or something like that.

Then, in the registrar's `finalize` method (around line 172), can you add this as the first line:
``` python
logger.warning(f"Registrar finalise: {self._finalized=}\n{lifecycle.behavior=}\n{self.windows=}")
```

**Comment by skela** [comment]
yeah i was already trying to do something to that effect - looks like windows is empty.

**Comment by elParaguayo** [comment]
Progress!

The issue is that `self.windows` is empty here. This should contain details of any windows that you've got open that have a global menu.

Was the menu working on your `code` window in that latest screenshot?

**Comment by skela** [comment]
Here's a better screenshot, this is me right after I've restarted qtile.
I've basically just restarted qtile as i had the global menu showing for vscode.

**Comment by elParaguayo** [comment]
That's odd. The `LOADED` message is appearing right before `registrar.finalize()`.  I really can't tell why that's happening!

**Comment by skela** [comment]
I forgot to add a logging line to the widget's finalize method, ive only got one for the registrar, let me do this one more time hang on

**Comment by skela** [comment]
Right... load does seem to be called before , as you said

.

**Comment by skela** [comment]
Not sure if this is helpful, but my gut feeling is that perhaps creating an instance of the registrar in the globalmenu.py file might be whats causing the issue.

**Comment by skela** [comment]
But what alternative location to create the instance, i havent a clue.
also cannot explain why it works for you but not for me, thats weird.

**Comment by elParaguayo** [comment]
Ah. Are you on a multi-screen setup? I hadn't tested that but, you're right, the registrar would need to be in a separate file otherwise it gets overwritten each time a widget is created.

Give me a few mins.

**Comment by skela** [comment]
Yeah ive got 2 monitors.

**Comment by elParaguayo** [comment]
> Yeah ive got 2 monitors.

OK - that last commit should (hopefully) fix the issue.

**Comment by skela** [comment]
@elParaguayo tested it 6 days ago, but also today, still the same "problem", but honestly i dont think its worth spending too much time on. This global menu widget of yours is pure genius.

Such a shame it cant be baked into qtile proper, i mean, the beautiful thing about tiling window managers is u dont need all the window decorations, but it leaves apps ugly with that menu bar at the top, which global menu's solve in a nice way.

But i've been using your solution for a while now, and ill continue to do so, i love it :D

**Comment by elParaguayo** [comment]
I've made a couple of tweaks. It works ok for me on a multi-monitor setup when doing both `restart` and `reload_config`.

If it's not working for you, can you give me some steps to follow and I'll try again.

**Comment by skela** [comment]
Yeah works for me too now... :D

**Comment by elParaguayo** [comment]
Awesome. Will tidy up the PR and get this merged.

**Pull request merged**
